language: ruby
rvm:
  - 2.1
# branch whitelist
branches:
  only:
  - master
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer