# Site settings
title: Rodrigo Alves
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Meu Blog"
baseurl: ""
url: "http://localhost:4000/"
twitter_username: rodrigo254mix
github_username:  rodrigo54
facebook_username:  rodrigo54
email_site: rodrigo54mix@gmail.com

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments
#permalink: pretty
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
