# Site settings
title: Blog do Rodrigo Alves
header-img: img/snapshot.jpg
email: rodrigo54mix@gmail.com
description: "Meu Blog"
baseurl: "http://blog.rodrigoalves.me/"

twitter_username: rodrigo254mix
github_username:  rodrigo54
facebook_username:  rodrigo54
linkedin_username: rodrigo54
email_site: rodrigo54mix@gmail.com
timezone: America/Fortaleza

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments
#permalink: pretty
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:
- jemoji