# Site settings
title: Blog do Rodrigo Alves
header-img: img/snapshot.jpg
email: rodrigo54mix@gmail.com
description: "Meu nome é Rodrigo Alves Mesquita, nasci em São Luis - MA, Sou um Web developer amante da Tecnologia que gosta de apreder novas formas de programar. Eterno aluno de C e PHP, tento me esforçar para ser um bom artista da web."
baseurl: "https://rodrigoalves.me/blog"

twitter_username: rodrigo254mix
github_username:  rodrigo54
facebook_username:  rodrigo54
linkedin_username: rodrigo54
email_site: rodrigo54mix@gmail.com
timezone: America/Fortaleza

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins:
- jemoji
- jekyll-paginate
