baseurl = "https://rodrigoalves.me/"
languageCode = "pt-BR"
title = "Blog do Rodrigo Alves"
canonifyurls = true
paginate = 5

disqusShortname = "rodrigo-io"
googleAnalytics = ""
theme = "clean-blog"
pygmentsStyle = "monokai"
pygmentsUseClassic = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Desenvolvedor Web"
  Author = "Rodrigo Alves Mesquita"
  email = "rodrigo54mix@gmail.com" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 3 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = true #set to false to exclude read time from header of post

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/rodrigo254mix"
[[params.social]]
  title = "github-alt"
  url = "https://github.com/rodrigo54"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/rodrigo54"
[[params.social]]
  title = "linkedin"
  url = "https://br.linkedin.com/in/rodrigo54"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200