[context.deploy-preview]
  command = "sed -i 's/DEPLOY_URL_PLACEHOLDER/$DEPLOY_PRIME_URL/g' netlify.toml && npm run build:static && hugo"
  publish = "public"

[context.deploy-preview.environment]
  HUGO_BASEURL = "DEPLOY_URL_PLACEHOLDER" 
  HUGO_VERSION = "0.38"