[build]
  command = "bun run build"
  publish = "dist/analog/public"
  environment = { DEPLOYED_ON_NETLIFY = "true" }

[context.branch.develop]
  command = "bun run build:develop"
  publish = "dist/analog/public"
