[context."hugo"]
  HUGO_BASEURL = "DEPLOY_URL_PLACEHOLDER" 
  command = "sed -i s/DEPLOY_URL_PLACEHOLDER/$DEPLOY_PRIME_URL/g netlify.toml && npm run build:static && hugo"
  publish = "public"
  HUGO_VERSION = "0.38"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.38"